monitoring_question_order = [
    "murder other religions",
    "murder coreligionists",
    "murder other polities",
    "non-lethal fighting",
    "honouring oaths",
    "shirking risk",
    "ritual observance",
    "performance of rituals",
    "sorcery",
    "lying",
    "gossiping",
    "personal hygiene",
    "laziness",
    "sex",
    "taboos",
    "economic fairness",
    "disrespecting elders",
    "property crimes",
    "prosocial norm adherence",
    "conversion non-religionists",
]
